### ISSUE TITLE
Switch from client-python to pykube

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-ops-view#112]
This looks much nicer and directly uses/supports the `requests` library: https://github.com/kelproject/pykube

**Comment by gtaylor** [comment]
Amusingly enough, we just switch from pykube to client-python for our stuff since the latter benefits substantially from its official status. Things like OIDC auth are flat out not supported in pykube, and it's unclear if development will continue now that client-python exists.

**Comment by hjacobs** [comment]
@gtaylor thanks for the information!

**Comment by hjacobs** [comment]
This issue is obsolete with #209
