### ISSUE TITLE
Discover kubernetes master when running kube-ops-view in cluster

### ISSUE THREAD

**Issue by JorritSalverda** [hjacobs/kube-ops-view#132]
Hi, I'm trying to run kube-ops-view in a GKE cluster without setting any of the environment variables.

Could you perhaps auto-detect the master from the envvar and token that gets mounted in any pod running in a cluster?

envvars:

- KUBERNETES_SERVICE_HOST
- KUBERNETES_PORT_443_TCP_PORT

The following mounted files can be used to authenticate to the master and trusts its certificate:

- /var/run/secrets/kubernetes.io/serviceaccount/token 
- /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

Until that works how would I configure the application to leverage those items?

**Comment by hjacobs** [comment]
@JorritSalverda this should work automatically. I'm using the Kubernetes Python client with `load_incluster_config()` to load the mentioned files, only if this fails it falls back to the default `kubectl proxy` URL, see https://github.com/hjacobs/kube-ops-view/blob/master/kube_ops_view/cluster_discovery.py#L70

Can you run it with `--debug` and show me the error? Please also check whether you are using the latest version (https://github.com/hjacobs/kube-ops-view/releases/tag/0.7.1 uploaded to Docker hub).

**Comment by JorritSalverda** [comment]
Yes it works. It seemed my cpu limit was too low!

**Comment by hjacobs** [comment]
@JorritSalverda great to hear! :smile: I would be glad to hear any feedback & suggestions: e.g. what information is missing for you in the view? We also have to improve the docs (https://kubernetes-operational-view.readthedocs.io/)  --- anything unclear, just ask (GH issue, I'll label as "question").
