### ISSUE TITLE
Empty ops view even though I get data

### ISSUE THREAD

**Issue by do3cc** [hjacobs/kube-ops-view#146]
Hi,

I am trying the kube ops view on openshift, with the fork from @raffaelespazzoli
After some permission problems I got it working that it starts and can access the api server.
It seems to get data because I get good looking data from the /events url, but the screen stays empty.
Is the data maybe incomplete?

[reduced_events_output.txt](https://github.com/hjacobs/kube-ops-view/files/1284586/reduced_events_output.txt)

**Comment by raffaelespazzoli** [comment]
I have the same problem with openshift 3.6. I have not figured out what the problem is.

**Comment by do3cc** [comment]
In my case, I do not see data because my local browsers computer is more than 5 minutes in the future to the node on which the kube-ops-view pod is running.

When querying the for the status, the date of the last check is taken in javascript from my browser.
When new data arrives, it gets compared with the timestamp as provided by the backend on the remote node.
After syncing the time, everything works.
I am not sure why these checks are there anyway and if instead of changing this it makes more sense to have a warning in the docs to make sure that clocks are mostly in sync. Something that one wants anyway.

**Comment by do3cc** [comment]
Ah and yes, not it works

**Comment by hjacobs** [comment]
@do3cc sorry to sound harsh, but I would assume that synced clocks (+/- seconds) are a requirement in 2017. There are a lot of other important things like one time tokens (OTP, like Google Authenticator uses) relying on synced clocks, i.e. there are probably more relevant things than kube-ops-view breaking without synced clocks :smirk:

**Comment by hjacobs** [comment]
@do3cc I'm still looking for someone to tell me how to get OpenShift/MiniShift "out of the box" working with Heapster metrics (see #137). I would gladly support OpenShift, but I don't have time to dig into the OpenShift specifics and how to set up metrics there.

**Comment by do3cc** [comment]
@hjacobs yeah it is a bit embarrassing not having synced clocks. Let's pretend that never happened.
@raffaelespazzoli has added support for openshift in a fork.
Apart from using different objects for declaring a complete kube-ops-project in openshift, it seems that Openshift has some APIs at a different endpoint:
```
 -        response = request(cluster, '/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/pods')
 +        response = request(cluster, 'api/v1/proxy/namespaces/openshift-infra/services/https:heapster:/apis/metrics/v1alpha1/pods')
```
The endpoints are documented as [Kubernetes API](https://docs.openshift.com/container-platform/3.5/rest_api/kubernetes_v1.html), but are clearly at different locations.
Also, after hunting for it without success yesterday, it seems that Openshift does not use the kubernetes-apiserver but provides the api server with its own program.
It seems that it makes sense to add a Openshift module next to the Kubernetes module.
With regards to minishift, I can't tell you, I don't have it running myself.

**Comment by do3cc** [comment]
At least for openshift, ntp is even a prereq.

I think I can close this ticket.
