### ISSUE TITLE
Feature request - separation of master and node pools

### ISSUE THREAD

**Issue by audip** [hjacobs/kube-ops-view#148]
First of all, I love the project and makes my life so much easier at work. One dashboard to look out for figuring things out. 
As a feature request, I'd like to see a separation of rows for master and node instances to make it clear and what is being scheduled where. When cluster grows to more than 15-20 nodes, it is hard to find information (search is great) but visually it will make things way easier.

**Comment by hjacobs** [comment]
I guess you realized that this is already implemented? `kube-ops-view` does not yet support the new well-known role labels, I therefore created https://github.com/hjacobs/kube-ops-view/issues/149

**Comment by audip** [comment]
Yes, I did.

**Comment by kaihendry** [comment]
I'm using this tool on a GKE cluster with workloads distributed amongst *node pools*, hence I was expecting the view the be grouped by node pool. Am I missing a trick here?

![image](https://user-images.githubusercontent.com/765871/68928095-3dcc3900-07c4-11ea-84da-fe695a50e60a.png)

**Comment by hjacobs** [comment]
@kaihendry the current logic only separates master from worker nodes hence you don't see a grouping by node pool. This would be a nice feature request, maybe create a separate issue for it?
