### ISSUE TITLE
"Running locally" instructions not working on MacOS

### ISSUE THREAD

**Issue by ahmetb** [hjacobs/kube-ops-view#150]
My workstation is macOS and I have a kubectl configured with a GKE cluster. I am using "Docker for Mac" to run kube-ops-view, but it’s not working according to the instructions in the "Running locally" section of the README.md.

```sh
$ kubectl proxy &
[1] 66292
Starting to serve on 127.0.0.1:8001
```

```
$ docker run -it --net=host hjacobs/kube-ops-view
Unable to find image 'hjacobs/kube-ops-view:latest' locally
latest: Pulling from hjacobs/kube-ops-view
0a8490d0dfd3: Pull complete
df1560d6f210: Pull complete
6ead5b210796: Pull complete
3a18deac42c6: Pull complete
09a8e2fbc07b: Pull complete
d99502978e82: Pull complete
8fbea2036c65: Pull complete
Digest: sha256:7e53625c370e705392b82316e976e2e08ec6d37952b1d03f2cad30c9cc0d2dab
Status: Downloaded newer image for hjacobs/kube-ops-view:latest
INFO:kube_ops_view.main:Listening on :8080..
ERROR:kube_ops_view.update:Failed to query cluster localhost:8001 (http://localhost:8001/): ConnectionError (try 1, wait 4 seconds)
ERROR:kube_ops_view.update:Failed to query cluster localhost:8001 (http://localhost:8001/): ConnectionError (try 2, wait 10 seconds)
ERROR:kube_ops_view.update:Failed to query cluster localhost:8001 (http://localhost:8001/): ConnectionError (try 3, wait 18 seconds)
ERROR:kube_ops_view.update:Failed to query cluster localhost:8001 (http://localhost:8001/): ConnectionError (try 4, wait 32 seconds)
ERROR:kube_ops_view.update:Failed to query cluster localhost:8001 (http://localhost:8001/): ConnectionError (try 5, wait 62 seconds)
```

Maybe consider making this directly runnable on the cluster, with `kubectl run --rm -i -t`? This way you can use in-cluster `https://kubernetes.default` service and the default service account to authenticate.

**Comment by hjacobs** [comment]
I guess "Docker for Mac" might be the problem here :smirk: 

I assume that `--net=host` only has access to localhost inside the VM, but `kubectl proxy` is listing on your host machine. Feel free to come up with some instructions for Docker for Mac users --- I use Linux :smile:

**Comment by ahmetb** [comment]
Got it.

I would consider making this dashboard runnable inside the Kubernetes cluster, which then we can use `kubectl port-forward` to access it locally.
