### ISSUE TITLE
Too many pods per node make box overflow

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-ops-view#151]
The node's box "overflows" If there are more than 42 pods on a single node.

![screenshot_2017-11-14_15-19-40](https://user-images.githubusercontent.com/510328/32784621-a1a2616c-c94f-11e7-8871-40b9d9a0a97b.png)

**Comment by holgerkoch** [comment]
It is complicated to calculate the right box size. Maybe it is a good way to static double the size of the node box. In my opinion, it is very rare, that more than hunderts containers running on a node.

best regards

Holger

**Comment by holgerkoch** [comment]
Hi there,

i look into the code some hours, but i can't find the right position. Maybe because i'm not a programmer :-)
It is easy to increase the size of the boxes to a 10x10 raster? Or can you give me a hint, where i should look for this?

best regards

Holger Koch

**Comment by tomislater** [comment]
Hey, glance at this PR: #208 please

**Comment by tomislater** [comment]
I think we can close this issue

**Comment by hjacobs** [comment]
For reference how the node size is adjusted now:
![screenshot_2019-03-06_20-25-32](https://user-images.githubusercontent.com/510328/53909185-686ccc00-4051-11e9-8023-7da78ebe8f9a.png)
