### ISSUE TITLE
Add hover info for pods

### ISSUE THREAD

**Issue by otrosien** [hjacobs/kube-ops-view#159]
For showing pod information:
* pod name
* labels
* heapster infos

**Comment by hjacobs** [comment]
This should generally work fine, see screenshot:

![screenshot_2018-03-07_22-19-10](https://user-images.githubusercontent.com/510328/37118813-befeb508-2255-11e8-8ebf-94782a63607e.png)

There is a known bug that hover infos stop working after changing the UI theme (reloading the webpage fixed it). Could you check whether you ran into this?

**Comment by otrosien** [comment]
The first thing I did was changing the theme, that's probably the reason.

**Comment by hjacobs** [comment]
Here the "theme switch" bug as reference: https://github.com/hjacobs/kube-ops-view/issues/69

**Comment by otrosien** [comment]
ok thanks, I'll close this issue.
