### ISSUE TITLE
Everybody loves screenshots :)

### ISSUE THREAD

**Issue by jeffersongirao** [hjacobs/kube-ops-view#16]
It would be nice to get some screenshots on the existing state of the dashboard.

Cheers!
J

**Comment by hjacobs** [comment]
@jeffersongirao sure, will do :smile: -- here a small preview from the current state (**WORK IN PROGRESS**)..
![screenshot_2016-12-19_21-04-14](https://cloud.githubusercontent.com/assets/510328/21327327/dc146aea-c62e-11e6-8cec-7cf9c0e8d12c.png)

**Comment by jeffersongirao** [comment]
Nice! Thanks @hjacobs

**Comment by hjacobs** [comment]
@jeffersongirao IMHO looks already much better now: https://twitter.com/try_except_/status/811697680879587330

**Comment by hjacobs** [comment]
Added a screenshot to the README.
