### ISSUE TITLE
Invalid oAuth credentials error on Openshift 3.6

### ISSUE THREAD

**Issue by raffian** [hjacobs/kube-ops-view#161]
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7

Getting invalid oAuth on Openshift 3.6. When running the proxy locally, I can curl for namespaces without bearer tokens and it works fine, not sure why when running ops-view it's having problems with oAuth.

```
$ oc proxy --address=0.0.0.0 &
$ curl http://localhost:8001/api/v1/namespaces
{
  "kind": "NamespaceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces",
    "resourceVersion": "24823672"
  },
  "items": [...]
```

Run proxy
`oc proxy --address=0.0.0.0  &`

Test proxy locally...
```
$ curl http://127.0.0.1:8001/api            
{                                           
  "kind": "APIVersions",                    
  "versions": [                             
    "v1"                                    
  ],                                        
  "serverAddressByClientCIDRs": [           
    {                                       
      "clientCIDR": "0.0.0.0/0",            
      "serverAddress": "ocnp.ny.ofi.com"    
    }                                       
```                                     

Run ops-view
`docker run -it --net=host -e CLUSTERS=http://127.0.0.1:8001/  raffaelespazzoli/ocp-ops-view`

Error:
```
ERROR:kube_ops_view.update:Failed to query cluster 127-0-0-1:8001 (http://127.0.0.1:8001): Invalid OAuth credentials: Failed to read token "read-only" from . (try 3, wait 17 seconds)
Traceback (most recent call last):
  File "/kube_ops_view/update.py", line 54, in update_clusters
    data = query_cluster(cluster)
  File "/kube_ops_view/kubernetes.py", line 67, in query_kubernetes_cluster
    response = request(cluster, '/api/v1/nodes')
  File "/kube_ops_view/kubernetes.py", line 57, in request
    return session.get(urljoin(cluster.api_server_url, path), auth=cluster.auth, verify=cluster.ssl_ca_cert, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/kube_ops_view/cluster_discovery.py", line 50, in __call__
    token = tokens.get(self.token_name)
  File "/usr/lib/python3.6/site-packages/tokens/__init__.py", line 165, in get
    refresh(token_name)
  File "/usr/lib/python3.6/site-packages/tokens/__init__.py", line 121, in refresh
    raise InvalidCredentialsError('Failed to read token "{}" from {}.'.format(token_name, path))
tokens.InvalidCredentialsError: Invalid OAuth credentials: Failed to read token "read-only" from 
```

**Comment by hjacobs** [comment]
I think the problem is here: https://github.com/hjacobs/kube-ops-view/blob/master/kube_ops_view/cluster_discovery.py#L88 

Could you try with `localhost` instead of `127.0.0.1` to see if it works?

**Comment by raffian** [comment]
Which API endpoint should kube-ops be using; `/api/v1/` or `/oapi/v1/`? Both appear to work when requesting directly (no proxy or kube-ops enabled). I'll try with localhost, but tell me something, when running `oc proxy` to remote kubernetes API, does the proxy use my credentials from last known login in my terminal session?

**Comment by hjacobs** [comment]
@raffian I'm not familiar with OpenShift, but I assume `oc proxy` works like `kubectl proxy` and uses your last known login credentials (`.kube/config`).

**Comment by raffian** [comment]
@hjacobs  [Openshift](https://github.com/openshift/origin) is the commercial version of Origin Kubernetes, and yes, `oc proxy` is the same as `kubectl proxy`.  You're saying use `localhost` for proxy and `CLUSTERS` address, basically, the default settings?

**Comment by raffian** [comment]
I got it working, remind me to never use DockerToolbox on windows ever again :-) 
Switched to Mac, followed instructions, everything works 100%, nice app!
