### ISSUE TITLE
Heapster is deprecated

### ISSUE THREAD

**Issue by towolf** [hjacobs/kube-ops-view#168]
On my cluster so far, only the Kube Dashboard is still using heapster (due to slow development I assume).

The other components are using the metrics-server aggregate api, when it is available:
https://github.com/kubernetes-incubator/metrics-server

The call used by `kubectl top nodes` is this:
`https://api.dev.k8s.goo.bar:8443/apis/metrics.k8s.io/v1beta1/nodes`

`kubectl top pods --all-namespace` uses this:
`https://api.dev.k8s.foo.bar:8443/apis/metrics.k8s.io/v1beta1/pods`

`kubectl top pods -n kube-system` uses this:
`https://api.dev.k8s.foo.bar:8443/apis/metrics.k8s.io/v1beta1/namespaces/kube-system/pods`

**Comment by hjacobs** [comment]
Relevant issue for Kubernetes Dashboard: https://github.com/kubernetes/dashboard/issues/2986

**Comment by towolf** [comment]
@hjacobs wasn't this closed by PR #177?

**Comment by hjacobs** [comment]
@towolf yes, but not released yet.

**Comment by zolij** [comment]
What's the eta for the release?

**Comment by hjacobs** [comment]
@zolij sorry, I dropped the ball, will follow up on it this week.

**Comment by hjacobs** [comment]
Released: https://github.com/hjacobs/kube-ops-view/releases/tag/0.9
