### ISSUE TITLE
URL Not correct?

### ISSUE THREAD

**Issue by kesterriley** [hjacobs/kube-ops-view#173]
When I install this on Kubernetes, and run the proxy, if I browse (as per the docs) to 

http://localhost:8001/api/v1/proxy/namespaces/default/services/kube-ops-view/

I get

```
kind | "Status"
-- | --
apiVersion | "v1"
metadata | {}
status | "Failure"
message | "the server could not find the requested resource"
reason | "NotFound"
details | {}
code | 404
```

However if I go to

http://localhost:8001/api/v1/namespaces/default/services/kube-ops-view

I get

```
kind | "Service"
-- | --
apiVersion | "v1"
metadata |  
name | "kube-ops-view"
namespace | "default"
selfLink | "/api/v1/namespaces/default/services/kube-ops-view"
uid | "aa3ef47f-a556-11e8-92a3-0050569a0b8d"
resourceVersion | "2501"
creationTimestamp | "2018-08-21T15:27:07Z"
labels |  
application | "kube-ops-view"
annotations |  
kubectl.kubernetes.io/last-applied-configuration | "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"labels\":{\"application\":\"kube-ops-view\"},\"name\":\"kube-ops-view\",\"namespace\":\"default\"},\"spec\":{\"ports\":[{\"port\":80,\"protocol\":\"TCP\",\"targetPort\":8080}],\"selector\":{\"application\":\"kube-ops-view\"},\"type\":\"NodePort\"}}\n"
spec |  
ports |  
0 |  
protocol | "TCP"
port | 80
targetPort | 8080
nodePort | 30106
selector |  
application | "kube-ops-view"
clusterIP | "10.102.136.168"
type | "NodePort"
sessionAffinity | "None"
externalTrafficPolicy | "Cluster"
status |  
loadBalancer | {}
```

What is the correct URL to browse to please?

**Comment by kesterriley** [comment]
OK, I have solved this - but when I run it - I get nothing displayed other than the header where I can just change the colour etc.

**Comment by miracle2k** [comment]
For me, the correct url was:

`http://localhost:8001/api/v1/namespaces/default/services/$SERVICE_NAME/proxy/`

(i.e. move the `/proxy` to to the end).

**Comment by d-mcd** [comment]
> For me, the correct url was:
> 
> `http://localhost:8001/api/v1/namespaces/default/services/$SERVICE_NAME/proxy/`
> 
> (i.e. move the `/proxy` to to the end).

Thank you @miracle2k ; was my issue

**Comment by hjacobs** [comment]
@miracle2k can you propose a fix via PR (for the README)? Thanks!

**Comment by kesterriley** [comment]
> I am having the same issue as you, @kesterriley :
> "OK, I have solved this - but when I run it - I get nothing displayed other than the header where I can just change the colour etc."
> How did you resolve it?

Hi @kylel  -- I never resolved it - I gave up in the end!

**Comment by hjacobs** [comment]
@miracle2k thanks for the URL hint, just tried it myself with DigitalOcean Kubernetes Beta and fixed the URL in the README :smile: 

![screenshot_2018-11-03_11-31-21](https://user-images.githubusercontent.com/510328/47951111-7f44ca00-df5c-11e8-8754-3f20c9a98253.png)

**Comment by kesterriley** [comment]
OK, I have tried again and this is also working for me!
