### ISSUE TITLE
Connection reset browsing to top-level

### ISSUE THREAD

**Issue by shuston** [hjacobs/kube-ops-view#178]
I installed kube-ops-view in my cluster. Afterwards I changed the route's hostname to one that can be resolved from outside the cluster and tried to browse to it. There's a flurry of activity on the status at the bottom of the browser then an error page "The connection was reset"

I don't see any errors logged in the pod - just health check updates.

**Comment by hjacobs** [comment]
Could you describe the problem with more details? (e.g. dump of your browsers network monitor/tab)

**Comment by shuston** [comment]
It was an issue with the way I had the route hostname created. It is working now.
