### ISSUE TITLE
Add Security Context

### ISSUE THREAD

**Issue by obeyler** [hjacobs/kube-ops-view#184]
Could you add a security context to be able to use kube ops view in a K8S cluster who has a restricted PodSecurityPolicy who only allow RunAsNoRoot for user

**Comment by obeyler** [comment]
@hjacobs I put a PR do do that
https://github.com/helm/charts/pull/9811

**Comment by hjacobs** [comment]
Thanks!

**Comment by hjacobs** [comment]
Fixed in https://github.com/hjacobs/kube-ops-view/commit/68dc33423409f164d07df1db1eadf20d7363fed6
