### ISSUE TITLE
OpsView Seems to be Reading CPU Usage Incorrectly?

### ISSUE THREAD

**Issue by joshw123** [hjacobs/kube-ops-view#187]
![screen shot 2018-12-17 at 13 54 16](https://user-images.githubusercontent.com/19779568/50096156-f7b2d200-020e-11e9-9592-92b5e5a6a6e8.png)

See Screenshot above, this seems to be since 0.9.3, we are running metrics server. Values in kubectl top seem to be okay.

**Comment by hjacobs** [comment]
Can you find out and post the raw value reported by Metrics Server? I suppose it's a missing/wrong resource parsing in https://github.com/hjacobs/kube-ops-view/blob/master/app/src/utils.js#L3

**Comment by hjacobs** [comment]
Released in https://github.com/hjacobs/kube-ops-view/releases/tag/0.9.1

**Comment by hjacobs** [comment]
Here the difference between v0.9 and v0.9.1:

![screenshot_2018-12-19 kubernetes operational view 0.9](https://user-images.githubusercontent.com/510328/50245248-42307c00-03d2-11e9-9a62-9f497a23c2cb.png)

![screenshot_2018-12-19 kubernetes operational view 0.9.1](https://user-images.githubusercontent.com/510328/50245246-42307c00-03d2-11e9-872d-ad81394f1f33.png)
