### ISSUE TITLE
Failed to query cluster

### ISSUE THREAD

**Issue by 030** [hjacobs/kube-ops-view#197]
deployed using stable helm chart
ingress enabled
kube-ops-view is empty
pod log indicates:

```
ERROR:kube_ops_view.update:Failed to query cluster 10-31-240-1:443 (https://10.31.240.1:443): 403 Forbidden (try 4, wait 33 seconds)
10.28.0.11 - - [2019-01-12 20:01:02] "GET / HTTP/1.1" 200 1393 0.001381
ERROR:kube_ops_view.update:Failed to query cluster 10-31-240-1:443 (https://10.31.240.1:443): 403 Forbidden (try 5, wait 61 seconds)
```

**Comment by 030** [comment]
Perhaps you could add to the readme what rbac privileges are required.

**Comment by hjacobs** [comment]
@030 the files under `deploy` contain everything necessary, including RBAC: https://github.com/hjacobs/kube-ops-view/blob/master/deploy/auth.yaml

Note: I haven't checked the Helm chart recently..

**Comment by 030** [comment]
Huh, but there is also a chart in the stable repository. Should I use this or the one from the stable/charts?

**Comment by hjacobs** [comment]
@030 I don't personally use Helm, so maybe just try the `kubectl apply -f` command as given in the README?

**Comment by 030** [comment]
So this is not maintained by you https://github.com/helm/charts/tree/master/stable/kube-ops-view?

**Comment by austinbv** [comment]
@030 take a look in the `values.yml` file for the helm chart https://github.com/helm/charts/blob/master/stable/kube-ops-view/values.yaml

There is an option to install the rbac rules. That should solve your problem

**Comment by 030** [comment]
Ok thanks I see the rbac snippet in the values.yaml
