### ISSUE TITLE
Oauth2: authorization doesn't have scope parameter

### ISSUE THREAD

**Issue by jarik2995** [hjacobs/kube-ops-view#198]
Some of Oauth2 authorization servers(like Google) has *scope* parameter as required, can you please include possibility to specify scope parameter in the OAuthRemoteAppWithRefresh function:
Current:
```
auth = OAuthRemoteAppWithRefresh(
    oauth,
    'auth',
    request_token_url=None,
    access_token_method='POST',
    access_token_url=os.getenv('ACCESS_TOKEN_URL'),
    authorize_url=AUTHORIZE_URL
)
```

To something like:
```
auth = OAuthRemoteAppWithRefresh(
    oauth,
    'auth',
    request_token_url=None,
    access_token_method='POST',
    access_token_url=os.getenv('ACCESS_TOKEN_URL'),
    authorize_url=AUTHORIZE_URL,
    request_token_params = {'scope': os.getenv('SCOPE')}
)
```
Scope example:
{'scope': 'https://www.googleapis.com/auth/gmail.readonly'}

**Comment by hjacobs** [comment]
Do you want to provide a PR?

**Comment by 030** [comment]
Huh, but there is also a chart in the stable repository. Should I use this or the one from the stable/charts?
