### ISSUE TITLE
blackscreen when setting dashboard=true 

### ISSUE THREAD

**Issue by phynias** [hjacobs/kube-ops-view#203]
when adding dashboard=true to the url all i get is a blank screen.
i notice this error only happens when setting this as well.
![screen shot 2019-01-30 at 5 26 17 pm](https://user-images.githubusercontent.com/10147213/52024069-4319fa80-24b4-11e9-9810-8c9ac9b70b05.png)

tried on both chrome and firefox

**Comment by hjacobs** [comment]
True, will fix! Thanks for reporting!

**Comment by hjacobs** [comment]
Fixed :smile: 
![screenshot_2019-03-06_21-27-47](https://user-images.githubusercontent.com/510328/53911477-cc45c380-4056-11e9-887c-a2d2f23ec318.png)

**Comment by hjacobs** [comment]
Released: https://github.com/hjacobs/kube-ops-view/releases/tag/0.10
