### ISSUE TITLE
Node resource usage always shows 0

### ISSUE THREAD

**Issue by MikeTomlin19** [hjacobs/kube-ops-view#231]
The bar for “Used” shows zero for both Ram and CPU for all nodes. I’ve verified this across several clusters and the last two versions of kube-ops-view. This is the case in K8s version 1.9 and 1.11, I have not tried a later version of K8s.

**Comment by hjacobs** [comment]
Can you check the logs? Do you have the correct Metrics API installed? Which Kubernetes distribution do you use? What is the output of `kubectl top nodes -v=9`?

**Comment by MikeTomlin19** [comment]
My fault - Looks like this was an issue with my metrics API in both OpenShift 3.9 and 3.11.  I will close the issue.

Thanks @hjacobs for a great tool. We use this as the first place to look during a failure and to teach new users about how kubernetes works.
