### ISSUE TITLE
Tooltip for node meters

### ISSUE THREAD

**Issue by ChristianLohmann** [hjacobs/kube-ops-view#29]
Node meters should have tooltips showing actual values (like 500 MiB of 16 GiB memory used).

**Comment by hjacobs** [comment]
Tooltips are now there, see screenshot: 
![screenshot_2016-12-21_22-59-08](https://cloud.githubusercontent.com/assets/510328/21407716/3a66f6b4-c7d1-11e6-8d3f-b043168d0b8b.png)
