### ISSUE TITLE
Sort pods by name?

### ISSUE THREAD

**Issue by hjacobs** [hjacobs/kube-ops-view#35]
Pods are currently unsorted, they are displayed in the same order as returned by the Kubernetes API server.

Should we sort them by name to be consistent? Or should we sort them by creation timestamp?

/cc @ChristianLohmann @shuaibiyy

**Comment by ChristianLohmann** [comment]
pods with the most critical resources/crashlooping at first

**Comment by hjacobs** [comment]
We can also add a UI option to select the sort mode:

* sort by name (default?)
* sort by age
* sort by memory requests/usage/limit
* sort by CPU requests/usage/limit

This might be helpful to find resource hungry pods.

**Comment by hjacobs** [comment]
@ChristianLohmann hmm, but that would make pods potentially "jump around". I would like to have a "stable" place by default (this fits reality better as containers are not "moving" when their status changes).

**Comment by ChristianLohmann** [comment]
ok, makes sense
