### ISSUE TITLE
Support for client-side certificates

### ISSUE THREAD

**Issue by jonmoter** [hjacobs/kube-ops-view#72]
In our Kubernetes clusters, we use client-side certs for authentication. I see that in the Readme it states:

> Note that authentication via client-certificates is currently not supported!

It would be great if that could be added.

In general, it would be great if the app could read a [kubeconfig file](http://kubernetes.io/docs/user-guide/kubeconfig-file/). Then you could specify a comma-separated lists of `contexts` to connect to via command-line arg or environment variable.

**Comment by hjacobs** [comment]
@jonmoter thanks for your interest in this tool!

I guess client-side certs is something we need to support.

FYI: I generally want to support "looking up" clusters in some "Cluster Registry", see #73

**Comment by hjacobs** [comment]
@jonmoter simple workaround for now: just use `kubectl proxy`, e.g. as a sidecar as in https://github.com/hjacobs/kube-ops-view/blob/master/deploy/deployment.yaml

**Comment by jonmoter** [comment]
Have you tried out using the [kubernetes python client](https://github.com/kubernetes-incubator/client-python)?  It looks like if you use that library, you could call:

```config.load_kube_config()```

and that would read in the kubeconfig file, certs, etc.

**Comment by hjacobs** [comment]
@jonmoter thanks, will check it out..

**Comment by hjacobs** [comment]
@jonmoter client-side certs are now supported when using the `--kubeconfig-path` flag, see https://kubernetes-operational-view.readthedocs.io/en/latest/multiple-clusters.html

Tested with Minikube (note the extra volume mount for `~/.minikube` to get the SSL certs into the Docker container):

```bash
$ docker run -it --net=host -v ~/.kube:/kube -v ~/.minikube:$HOME/.minikube hjacobs/kube-ops-view:0.2.0 --kubeconfig-path=/kube/config --kubeconfig-contexts=minikube

**Comment by jonmoter** [comment]
Awesome, thank you!
