### ISSUE TITLE
Does not work on Safari due to absence of fetch support

### ISSUE THREAD

**Issue by shuaibiyy** [hjacobs/kube-ops-view#8]
See http://caniuse.com/#feat=fetch

**Comment by hjacobs** [comment]
Isn't Safari the new Internet Explorer? :smirk:

**Comment by hjacobs** [comment]
We are now using EventSource instead of Fetch, so it looks better for Safari now: http://caniuse.com/#feat=eventsource

**Comment by hjacobs** [comment]
@shuaibiyy can you confirm that it works for you with Safari?
